CREATE DATABASE COURSE30;
USE COURSE30;

CREATE TABLE PASSENGER
(
PASS_ID INT PRIMARY KEY,
PASS_NAME VARCHAR(45),
PASS_MOBILE  BIGINT,
PASS_COST INT,
TIME_ARRIVAL DATETIME,
PASS_DEPARTURES VARCHAR(35)
);

CREATE TABLE OLA
(
OLA_CAB_ID INT PRIMARY KEY,
DRIVER_NAME VARCHAR(35),
DRIVER_MOBILE BIGINT,
D_LOCATION VARCHAR(45),
VEHICAL_NUMBER_PLATE INT,
DEPARTURE_TIME_WITH_LOCATION VARCHAR(35),
D_RESERVE ENUM("T","F"),
D_BOOKED ENUM("YES","NO"),
D_OCCUPED ENUM("T","F"),
D_CASH_ONLION VARCHAR(35)
);

SELECT * FROM PASSENGER
INNER JOIN OLA
ON PASSENGER.PASS_ID = OLA.OLA_CAB_ID;

SELECT * FROM PASSENGER
LEFT JOIN OLA
ON PASSENGER.PASS_ID = OLA.OLA_CAB_ID;


SELECT * FROM course30.ola;

SELECT * FROM course30.passenger;



