CREATE TABLE EMP
(
EMP_ID INT,
FIRST_NAME VARCHAR(45),
LAST_NAME VARCHAR(45),
SALARY INT,
DEPARTMENT VARCHAR(45)
);
SELECT * FROM EMP;
INSERT INTO EMP(EMP_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)VALUES(1,"KRISHNA","GADHIYA",50000,"HR");
INSERT INTO EMP(EMP_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)VALUES(2,"GOPI","GADHIYA",40000,"ADMIN");
INSERT INTO EMP(EMP_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)VALUES(3,"DHARA","GADHIYA",70000,"MANAGER");
INSERT INTO EMP(EMP_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)VALUES(4,"PIYA","KHUNT",60000,"HR");
DROP TABLE EMP ;
SELECT * FROM EMP LIMIT 4;
SELECT * FROM EMP WHERE FIRST_NAME LIKE "%A" ;
SELECT * FROM EMP WHERE LAST_NAME LIKE "G%" ;
SELECT * FROM EMP WHERE DEPARTMENT LIKE "H%" ;
SELECT * FROM EMP WHERE FIRST_NAME LIKE "%SH%" ;
SELECT * FROM EMP WHERE FIRST_NAME LIKE "%IY%" ;
SELECT * FROM EMP WHERE FIRST_NAME NOT LIKE "%IY%" ;
SELECT * FROM EMP ORDER BY EMP_ID ASC ;
SELECT * FROM EMP ORDER BY SALARY ASC ;
SELECT * FROM EMP ORDER BY SALARY DESC ;
SELECT * FROM EMP ORDER BY DEPARTMENT ASC ;
SELECT * FROM EMP ORDER BY DEPARTMENT DESC ;
SELECT * FROM EMP ORDER BY FIRST_NAME ASC ;
SELECT * FROM EMP ORDER BY FIRST_NAME DESC ;
SELECT * FROM EMP ORDER BY LAST_NAME ASC ;
SELECT MIN(SALARY) FROM EMP ;
SELECT MAX(SALARY)FROM EMP ;
SELECT MAX(SALARY)AS MAXIMUM_TUES FROM EMP ;
SELECT SUM(SALARY)AS COUNT_TUES FROM EMP ;
SELECT AVG(SALARY)AS AVERAGE_TUES FROM EMP ;
SELECT DISTINCT FIRST_NAME FROM EMP ;
SELECT DISTINCT LAST_NAME FROM EMP ;
SELECT DISTINCT DEPARTMENT FROM EMP ;
SELECT DISTINCT SALARY FROM EMP ;








