USE COURSE30;

CREATE TABLE NAMEE
(
M_ID INT PRIMARY KEY,
M_NAME VARCHAR(35),
M_SALARY INT
);
SELECT * FROM NAMEE;
SELECT MAX(M_SALARY) FROM NAMEE ;
SELECT MIN(M_SALARY) FROM NAMEE ;
SELECT AVG(M_SALARY)AS AVERAGE_TUES FROM NAMEE ;
