USE COMPANY ;
CREATE TABLE WORKER3
(
WORKER_ID INT,
FIRST_NAME VARCHAR(45),
LAST_NAME VARCHAR(45),
SALARY INT,
JOING_DATE DATE,
DEPARTMENT VARCHAR(45)
);
SELECT * FROM WORKER3;
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(1,"MONIKA","ARORA",100000,"2014-02-20","HR");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(2,"NIHARIKA","VERMA",80000,"2014-11-06","ADMIN");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(3,"VISHAL","SINGHAL",300000,"2014-02-20","HR");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(4,"AMITABH","SINGH",500000,"2014-02-20","ADMIN");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(5,"VIVEK","BHATI",500000,"2014-11-06","ADMIN");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(6,"VIPUL","DIWAN",200000,"2014-11-06","ACCOUNT");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(7,"SATISH","KUMAR",75000,"2014-01-20","ACCOUNT");
INSERT INTO WORKER3 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOING_DATE, DEPARTMENT)VALUES(8,"GEETIKA","CHAUHAN",90000,"2014-11-04","ADMIN");
SELECT * FROM WORKER3 ORDER BY FIRST_NAME ASC,DEPARTMENT DESC ;
SELECT * FROM WORKER3 ORDER BY DEPARTMENT DESC ;
SELECT * FROM WORKER3 WHERE FIRST_NAME LIKE "V%L" ;
SELECT * FROM WORKER3 WHERE FIRST_NAME LIKE "S%H" ;
SELECT * FROM WORKER3 WHERE FIRST_NAME LIKE "%H" ;
SELECT * FROM WORKER3 LIMIT 6;
SELECT MAX(SALARY) FROM WORKER3 ;
SELECT * FROM WORKER3 WHERE WORKER_ID;










